### Varying D for monthly aggregation
params:
  model_type: "monthly_large_plant"
  b_w: [.01,.02,.03,.04,.05,.06,.07,.08,.09,.1]
  b_b: [.01,.02,.03,.04,.05,.06,.07,.08,.09,.1]
  alpha: [0.1]
  deltaT: 1
  L: [3]
  T: 425
  P: [625]
  prop_fn: "../params/pub_clean_prop_dat.csv"
  net_file: "../params/yearly_agg_dat.csv"
  inc_file: "../params/inc_data/raw_data.csv"
  save_folder: ""
  D: [0.2,0.4,0.6,0.8]
  pool_amount: 40
  max_infected: 2300
  run_type: "calib"

