### Seasonal L variation
params:
  model_type: "seasonal_L_vary"
  b_b: [0.03]
  b_w: [0.08]
  alpha: [0.1,0.3,0.5,0.7,0.9]
  deltaT: 3
  T: 425
  L: [3]
  P: [625]
  prop_fn: "../params/pub_clean_prop_dat.csv"
  net_file: "../params/yearly_clean_agg.csv"
  inc_file: "../params/raw_data.csv"
  save_folder: ""
  D: [0.8]
  run_type: "run"
  pool_amount: 40
  max_infected: 3000


