### month vary sm
params:
  model_type: "month_vary"
  b_b: [0.03]
  b_w: [0.09]
  alpha: [0.1]
  deltaT: 1
  T: 425
  P: [625]
  L: [3]
  prop_fn: "../params/clean_prop_dat.csv"
  net_file: "../params/yearly_clean_agg.csv"
  inc_file: "../params/raw_data.csv"
  save_folder: "../results/best_m/"
  D: [0.4]
  run_type: "calib"
  pool_amount: 50
  max_infected: 3000


