###seasonal best vary ma
params:
  model_type: "season_vary"
  b_b: [0.03]
  b_w: [0.07]
  alpha: [0.1]
  deltaT: 3
  T: 425
  P: [625]
  L: [3]
  prop_fn: "../params/pub_clean_prop_dat.csv"
  net_file: "../params/yearly_clean_agg.csv"
  inc_file: "../params/ma_data.csv"
  save_folder: "../results/best_s_ma/"
  D: [0.8]
  run_type: "calib"
  pool_amount: 50
  max_infected: 3000


